title = "metadata for oscar CI run"

[env]
  os = [ ["Linux", "RPTU", "normal-memory"] ]
# julia-version = [ "~1.6.0-0"]
# branches = [ "release", "<matching>" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Hecke]
  test = false

[include]
  [include.justoscarmaster]
  Oscar = "master"
  Hecke = "release"
  julia-version = "1.10"
  os = ["Linux", "RPTU", "normal-memory"]
