name = "GAP"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
authors = ["Thomas Breuer <sam@math.rwth-aachen.de>", "Sebastian Gutsche <gutsche@mathematik.uni-siegen.de>", "Max Horn <horn@mathematik.uni-kl.de>"]
version = "0.13.0-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GAP_jll = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
GAP_lib_jll = "de1ad85e-c930-5cd4-919d-ccd3fcafd1a3"
GAP_pkg_juliainterface_jll = "ba154793-3a7d-51ee-8800-e295b0cf7374"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Ncurses_jll = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
Pidfile = "fa939f87-e72e-5be4-a000-7fc836dbe307"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
AbstractAlgebra = "0.41.11, 0.42.1, 0.43"
Artifacts = "1.6"
Compat = "4.4.0"
Dates = "1.6"
Downloads = "1.4.3"
GAP_jll = "~400.1400.000"
GAP_lib_jll = "~400.1400.000"
GAP_pkg_juliainterface_jll = "=0.1300.0"
InteractiveUtils = "1.6"
Libdl = "1.6"
MacroTools = "0.5.13"
Markdown = "1.6"
Ncurses_jll = "6.4.1"
Pidfile = "1.3"
Pkg = "1.6"
REPL = "1.6"
Random = "1.6"
Scratch = "1.1"
TOML = "<0.0.1, 1"
julia = "1.6"
